export interface TarotCard {
  id: number;
  name: string;
  nameZh: string;
  arcana: "major" | "minor";
  suit?: "wands" | "cups" | "swords" | "pentacles";
  number?: number;
  keywords: string[];
  keywordsReversed: string[];
  imageEmoji: string;
  meaning: string;
  meaningReversed: string;
}

// ── 大阿卡纳 22张 ──
export const MAJOR_ARCANA: TarotCard[] = [
  { id: 0, name: "The Fool", nameZh: "愚者", arcana: "major", number: 0, imageEmoji: "🌟",
    keywords: ["新开始", "冒险", "自由", "纯真"], keywordsReversed: ["鲁莽", "犹豫", "风险"],
    meaning: "象征新的开始、无限可能与纯真的冒险精神。勇敢迈出第一步。",
    meaningReversed: "可能过于冲动或缺乏计划，需要停下来思考。" },
  { id: 1, name: "The Magician", nameZh: "魔法师", arcana: "major", number: 1, imageEmoji: "✨",
    keywords: ["意志力", "技能", "创造", "显化"], keywordsReversed: ["操控", "能力未发挥", "欺骗"],
    meaning: "你拥有实现目标所需的一切工具。专注意志，将想法化为现实。",
    meaningReversed: "能量分散或技能未被充分利用，检视自己的动机。" },
  { id: 2, name: "The High Priestess", nameZh: "女祭司", arcana: "major", number: 2, imageEmoji: "🌙",
    keywords: ["直觉", "神秘", "内在智慧", "潜意识"], keywordsReversed: ["压抑直觉", "秘密", "表面化"],
    meaning: "聆听内心深处的声音，相信自己的直觉。答案已在你心中。",
    meaningReversed: "忽视内心声音，过于依赖外部意见。" },
  { id: 3, name: "The Empress", nameZh: "女皇", arcana: "major", number: 3, imageEmoji: "🌸",
    keywords: ["丰盛", "创造力", "养育", "大自然"], keywordsReversed: ["依赖", "创意阻塞", "忽视自我"],
    meaning: "丰盛与创造的能量环绕你。这是成长、繁荣和爱的时刻。",
    meaningReversed: "需要关注自我照顾，可能感到创意受阻。" },
  { id: 4, name: "The Emperor", nameZh: "皇帝", arcana: "major", number: 4, imageEmoji: "👑",
    keywords: ["权威", "结构", "稳定", "领导力"], keywordsReversed: ["控制欲", "僵化", "缺乏纪律"],
    meaning: "建立稳固的基础，以权威和智慧领导。秩序带来力量。",
    meaningReversed: "检视是否过于控制，或缺乏必要的结构。" },
  { id: 5, name: "The Hierophant", nameZh: "教皇", arcana: "major", number: 5, imageEmoji: "🕍",
    keywords: ["传统", "智慧", "精神指引", "习俗"], keywordsReversed: ["打破传统", "非传统", "质疑权威"],
    meaning: "寻求传统智慧的指引，或向有经验的导师学习。",
    meaningReversed: "可能需要挑战传统，走自己的道路。" },
  { id: 6, name: "The Lovers", nameZh: "恋人", arcana: "major", number: 6, imageEmoji: "💕",
    keywords: ["爱情", "选择", "和谐", "价值观"], keywordsReversed: ["失衡", "错误选择", "价值观冲突"],
    meaning: "面临重要选择，跟随内心做出与价值观一致的决定。",
    meaningReversed: "关系中可能存在不和谐，或面临艰难抉择。" },
  { id: 7, name: "The Chariot", nameZh: "战车", arcana: "major", number: 7, imageEmoji: "⚡",
    keywords: ["意志力", "胜利", "决心", "控制"], keywordsReversed: ["失控", "侵略性", "缺乏方向"],
    meaning: "以坚定的意志克服障碍，胜利就在眼前。保持专注前行。",
    meaningReversed: "可能感到失去方向，需要重新聚焦目标。" },
  { id: 8, name: "Strength", nameZh: "力量", arcana: "major", number: 8, imageEmoji: "🦁",
    keywords: ["内在力量", "勇气", "耐心", "慈悲"], keywordsReversed: ["软弱", "自我怀疑", "能量耗尽"],
    meaning: "真正的力量来自内心的柔软与勇气。以爱和耐心驾驭挑战。",
    meaningReversed: "可能感到精力不足，需要补充内在力量。" },
  { id: 9, name: "The Hermit", nameZh: "隐士", arcana: "major", number: 9, imageEmoji: "🕯️",
    keywords: ["内省", "独处", "智慧", "寻求真理"], keywordsReversed: ["孤立", "拒绝帮助", "迷失"],
    meaning: "退入内心，独自寻找答案。智慧在安静中显现。",
    meaningReversed: "过度孤立可能带来迷失，适时接受他人的光。" },
  { id: 10, name: "Wheel of Fortune", nameZh: "命运之轮", arcana: "major", number: 10, imageEmoji: "🎡",
    keywords: ["命运", "转机", "循环", "好运"], keywordsReversed: ["不幸", "抗拒变化", "坏运气"],
    meaning: "命运的轮盘转动，好运正在降临。拥抱变化，顺应宇宙的节奏。",
    meaningReversed: "暂时的低潮，但轮盘终将再次转向光明。" },
  { id: 11, name: "Justice", nameZh: "正义", arcana: "major", number: 11, imageEmoji: "⚖️",
    keywords: ["公正", "真相", "因果", "平衡"], keywordsReversed: ["不公正", "逃避责任", "不诚实"],
    meaning: "因果法则运作，诚实面对自己。公正将得到伸张。",
    meaningReversed: "检视是否逃避责任，或面临不公的情况。" },
  { id: 12, name: "The Hanged Man", nameZh: "倒吊人", arcana: "major", number: 12, imageEmoji: "🙃",
    keywords: ["暂停", "放手", "新视角", "牺牲"], keywordsReversed: ["拖延", "抗拒", "无谓牺牲"],
    meaning: "暂时停下来，从不同角度看待问题。放手才能获得新的领悟。",
    meaningReversed: "可能在拖延重要决定，或做出无谓的牺牲。" },
  { id: 13, name: "Death", nameZh: "死神", arcana: "major", number: 13, imageEmoji: "🦋",
    keywords: ["转变", "结束", "重生", "放下"], keywordsReversed: ["抗拒变化", "停滞", "恐惧"],
    meaning: "一个阶段结束，更美好的新开始即将到来。放下过去，拥抱蜕变。",
    meaningReversed: "抗拒必要的改变，阻碍了成长与蜕变。" },
  { id: 14, name: "Temperance", nameZh: "节制", arcana: "major", number: 14, imageEmoji: "🌈",
    keywords: ["平衡", "耐心", "调和", "中庸"], keywordsReversed: ["失衡", "过度", "缺乏耐心"],
    meaning: "寻找平衡与和谐，耐心让一切流动。走向正中之路。",
    meaningReversed: "可能在某方面过度，需要寻找更好的平衡点。" },
  { id: 15, name: "The Devil", nameZh: "恶魔", arcana: "major", number: 15, imageEmoji: "🔗",
    keywords: ["束缚", "物质主义", "阴影", "欲望"], keywordsReversed: ["解脱", "觉醒", "克服恐惧"],
    meaning: "审视是什么在束缚你。这些链条或许比想象中更容易挣脱。",
    meaningReversed: "正在从束缚中解脱，觉醒的时刻到来。" },
  { id: 16, name: "The Tower", nameZh: "塔", arcana: "major", number: 16, imageEmoji: "⛈️",
    keywords: ["突变", "破坏", "启示", "混乱"], keywordsReversed: ["逃避灾难", "恐惧变化", "延迟"],
    meaning: "突如其来的变化打破旧有结构，但废墟上将建起更坚固的基础。",
    meaningReversed: "可能在拖延不可避免的改变，越晚越难。" },
  { id: 17, name: "The Star", nameZh: "星星", arcana: "major", number: 17, imageEmoji: "⭐",
    keywords: ["希望", "灵感", "平静", "更新"], keywordsReversed: ["失去希望", "绝望", "不信任"],
    meaning: "黑暗之后，星光照耀。保持希望，宇宙正在更新与疗愈你。",
    meaningReversed: "暂时失去方向，但星光从未熄灭，重拾希望吧。" },
  { id: 18, name: "The Moon", nameZh: "月亮", arcana: "major", number: 18, imageEmoji: "🌕",
    keywords: ["幻象", "恐惧", "潜意识", "梦境"], keywordsReversed: ["混乱消散", "真相显现", "恐惧减少"],
    meaning: "事情并非表面那样。深入潜意识，面对内心的恐惧与幻象。",
    meaningReversed: "迷雾正在散去，真相即将显现。" },
  { id: 19, name: "The Sun", nameZh: "太阳", arcana: "major", number: 19, imageEmoji: "☀️",
    keywords: ["喜悦", "成功", "活力", "光明"], keywordsReversed: ["短暂悲观", "延迟成功", "内心阴暗"],
    meaning: "最积极的牌！喜悦、成功与光明降临。全力拥抱这美好时刻。",
    meaningReversed: "成功可能稍有延迟，但阳光终将穿透云层。" },
  { id: 20, name: "Judgement", nameZh: "审判", arcana: "major", number: 20, imageEmoji: "🎺",
    keywords: ["觉醒", "更新", "赦免", "召唤"], keywordsReversed: ["自我怀疑", "无法原谅", "忽视召唤"],
    meaning: "觉醒的号角吹响！原谅过去，回应内心的召唤，走向新生。",
    meaningReversed: "检视是否在逃避内心深处的呼唤。" },
  { id: 21, name: "The World", nameZh: "世界", arcana: "major", number: 21, imageEmoji: "🌍",
    keywords: ["完成", "整合", "成就", "圆满"], keywordsReversed: ["未完成", "寻找捷径", "缺乏圆满"],
    meaning: "一个完美的循环圆满完成。你已达到重要的里程碑，值得庆祝！",
    meaningReversed: "旅程尚未结束，还有一些功课需要完成。" },
];

// ── 权杖（火）14张 ──
const WANDS: TarotCard[] = [
  { id: 22, name: "Ace of Wands", nameZh: "权杖王牌", arcana: "minor", suit: "wands", number: 1, imageEmoji: "🔥",
    keywords: ["新灵感", "创业", "激情", "潜力"], keywordsReversed: ["延误", "缺乏方向", "创意受阻"],
    meaning: "充满激情的新开始，一个大胆的创意等待你去点燃。",
    meaningReversed: "计划受阻，先打好基础再出发。" },
  { id: 23, name: "Two of Wands", nameZh: "权杖二", arcana: "minor", suit: "wands", number: 2, imageEmoji: "🌐",
    keywords: ["规划", "扩张", "远见", "决策"], keywordsReversed: ["恐惧未知", "缺乏计划", "原地踏步"],
    meaning: "站在高处眺望世界，大胆规划未来，准备迈向更广阔的天地。",
    meaningReversed: "对未知感到恐惧，需要克服内心障碍才能前进。" },
  { id: 24, name: "Three of Wands", nameZh: "权杖三", arcana: "minor", suit: "wands", number: 3, imageEmoji: "⛵",
    keywords: ["扩展", "远航", "等待结果", "领导"], keywordsReversed: ["延误", "障碍", "预期落空"],
    meaning: "已经迈出步伐，耐心等待努力的回报，好消息正在途中。",
    meaningReversed: "计划遇到意外障碍，需要重新调整策略。" },
  { id: 25, name: "Four of Wands", nameZh: "权杖四", arcana: "minor", suit: "wands", number: 4, imageEmoji: "🎊",
    keywords: ["庆祝", "家园", "稳定", "里程碑"], keywordsReversed: ["内部冲突", "不稳定", "庆祝受阻"],
    meaning: "值得庆祝的时刻！家庭和谐，为你的成就鼓掌。",
    meaningReversed: "家庭或团队内部有摩擦，需要修复关系。" },
  { id: 26, name: "Five of Wands", nameZh: "权杖五", arcana: "minor", suit: "wands", number: 5, imageEmoji: "🤼",
    keywords: ["竞争", "冲突", "挑战", "磨练"], keywordsReversed: ["避免冲突", "内部矛盾", "混乱"],
    meaning: "竞争与挑战正在磨砺你。这是成长的摩擦，不必害怕。",
    meaningReversed: "可能在逃避必要的冲突，或内部矛盾激化。" },
  { id: 27, name: "Six of Wands", nameZh: "权杖六", arcana: "minor", suit: "wands", number: 6, imageEmoji: "🏆",
    keywords: ["胜利", "认可", "成功", "自信"], keywordsReversed: ["自我怀疑", "失败", "缺乏认可"],
    meaning: "你的努力得到了认可，胜利凯旋！享受这属于你的荣耀时刻。",
    meaningReversed: "可能面临挫折，或对自己的成就缺乏信心。" },
  { id: 28, name: "Seven of Wands", nameZh: "权杖七", arcana: "minor", suit: "wands", number: 7, imageEmoji: "🛡️",
    keywords: ["坚持", "捍卫立场", "压力", "优势"], keywordsReversed: ["放弃", "被压倒", "妥协"],
    meaning: "坚守自己的立场。相信自己，不要被压力击倒。",
    meaningReversed: "感到被质疑和压迫，考虑是否值得继续坚守。" },
  { id: 29, name: "Eight of Wands", nameZh: "权杖八", arcana: "minor", suit: "wands", number: 8, imageEmoji: "💨",
    keywords: ["速度", "快速进展", "行动", "消息"], keywordsReversed: ["延误", "挫折", "信息混乱"],
    meaning: "事情快速推进！行动的时机已到，好消息即将传来。",
    meaningReversed: "计划遇到延误或阻碍，需要耐心等待时机。" },
  { id: 30, name: "Nine of Wands", nameZh: "权杖九", arcana: "minor", suit: "wands", number: 9, imageEmoji: "🤕",
    keywords: ["坚韧", "接近终点", "防御", "疲惫"], keywordsReversed: ["崩溃", "固执", "偏执"],
    meaning: "虽然疲惫，但你快到终点了。再坚持一下，胜利就在前方。",
    meaningReversed: "因过度防御而陷入固执，学会适当放松。" },
  { id: 31, name: "Ten of Wands", nameZh: "权杖十", arcana: "minor", suit: "wands", number: 10, imageEmoji: "😓",
    keywords: ["重担", "过度责任", "负担", "压力"], keywordsReversed: ["放下重担", "委派", "解脱"],
    meaning: "你承担了太多。是时候放下一些，或寻求帮助。",
    meaningReversed: "正在学会放手，终于获得了喘息的机会。" },
  { id: 32, name: "Page of Wands", nameZh: "权杖侍者", arcana: "minor", suit: "wands", imageEmoji: "🌱",
    keywords: ["热情", "探索", "好奇心", "新消息"], keywordsReversed: ["冲动", "缺乏方向", "鲁莽"],
    meaning: "充满好奇心的探索者！新的灵感或机会正在向你招手。",
    meaningReversed: "热情有余但缺乏计划，需要更多思考再行动。" },
  { id: 33, name: "Knight of Wands", nameZh: "权杖骑士", arcana: "minor", suit: "wands", imageEmoji: "🏇",
    keywords: ["行动", "冒险", "能量", "追求"], keywordsReversed: ["鲁莽", "冲动", "缺乏耐心"],
    meaning: "充满活力，快速行动！全速追逐你的激情。",
    meaningReversed: "行动过于冲动，可能因缺乏耐心而犯错。" },
  { id: 34, name: "Queen of Wands", nameZh: "权杖皇后", arcana: "minor", suit: "wands", imageEmoji: "👸",
    keywords: ["自信", "魅力", "领导", "热情"], keywordsReversed: ["自私", "嫉妒", "支配欲"],
    meaning: "充满魅力与自信的领导者。你的热情感染着周围的人。",
    meaningReversed: "可能在用控制代替领导，或感到嫉妒。" },
  { id: 35, name: "King of Wands", nameZh: "权杖国王", arcana: "minor", suit: "wands", imageEmoji: "🦊",
    keywords: ["远见", "创业精神", "创新", "掌控"], keywordsReversed: ["霸道", "自大", "专制"],
    meaning: "有远见的领导者，用创造力和魄力开创事业。",
    meaningReversed: "需警惕因过于强势而失去团队的支持。" },
];

// ── 圣杯（水）14张 ──
const CUPS: TarotCard[] = [
  { id: 36, name: "Ace of Cups", nameZh: "圣杯王牌", arcana: "minor", suit: "cups", number: 1, imageEmoji: "💧",
    keywords: ["新感情", "直觉", "爱", "情感流动"], keywordsReversed: ["情感封闭", "失恋", "内心空虚"],
    meaning: "爱与情感的新开始。心灵向爱敞开，直觉告诉你这是真实的感受。",
    meaningReversed: "情感上有所封闭，需要自我疗愈。" },
  { id: 37, name: "Two of Cups", nameZh: "圣杯二", arcana: "minor", suit: "cups", number: 2, imageEmoji: "🥂",
    keywords: ["联结", "伙伴关系", "相互吸引", "和谐"], keywordsReversed: ["破裂", "失衡", "误解"],
    meaning: "两颗心的深度联结，爱情或友情中的美好共鸣。珍视这份缘分。",
    meaningReversed: "关系中出现失衡或误解，需要坦诚沟通。" },
  { id: 38, name: "Three of Cups", nameZh: "圣杯三", arcana: "minor", suit: "cups", number: 3, imageEmoji: "🎉",
    keywords: ["庆祝", "友谊", "社群", "喜悦"], keywordsReversed: ["过度放纵", "流言", "三角关系"],
    meaning: "与好友共同庆祝！友谊、欢乐与社群的美好时光。",
    meaningReversed: "可能有第三者介入，或小圈子中的流言蜚语。" },
  { id: 39, name: "Four of Cups", nameZh: "圣杯四", arcana: "minor", suit: "cups", number: 4, imageEmoji: "😑",
    keywords: ["冷漠", "内省", "不满足", "错过机会"], keywordsReversed: ["重新投入", "新机会", "觉醒"],
    meaning: "你在反思，但小心别因此错过身边的好机会。保持开放的心态。",
    meaningReversed: "从冷漠中走出，重新对生活感到热情。" },
  { id: 40, name: "Five of Cups", nameZh: "圣杯五", arcana: "minor", suit: "cups", number: 5, imageEmoji: "😢",
    keywords: ["失落", "悲伤", "后悔", "损失"], keywordsReversed: ["接受", "前行", "放下悲伤"],
    meaning: "允许自己悲伤，但别忘记身后还有两杯完好的希望。",
    meaningReversed: "走出悲伤，开始转身看见还剩下的美好。" },
  { id: 41, name: "Six of Cups", nameZh: "圣杯六", arcana: "minor", suit: "cups", number: 6, imageEmoji: "🌺",
    keywords: ["童年", "怀旧", "纯真", "旧友重逢"], keywordsReversed: ["活在过去", "天真", "停滞"],
    meaning: "美好的回忆滋养着你。旧友或童年的纯真带来温暖。",
    meaningReversed: "可能过度沉溺于过去，需要关注当下。" },
  { id: 42, name: "Seven of Cups", nameZh: "圣杯七", arcana: "minor", suit: "cups", number: 7, imageEmoji: "🌈",
    keywords: ["幻想", "选择", "迷失", "梦想"], keywordsReversed: ["清醒", "现实检查", "专注"],
    meaning: "你有太多选择和幻想。需要从梦境回到现实，专注于真正重要的。",
    meaningReversed: "从幻想中清醒，开始脚踏实地地追求真实目标。" },
  { id: 43, name: "Eight of Cups", nameZh: "圣杯八", arcana: "minor", suit: "cups", number: 8, imageEmoji: "🚶",
    keywords: ["离开", "寻求更多", "放弃", "内心追求"], keywordsReversed: ["恐惧离开", "停滞", "优柔寡断"],
    meaning: "你知道某些东西已不再满足你，勇敢离开，去寻找更深的满足。",
    meaningReversed: "知道该离开却迈不出步伐，恐惧让你原地踏步。" },
  { id: 44, name: "Nine of Cups", nameZh: "圣杯九", arcana: "minor", suit: "cups", number: 9, imageEmoji: "😊",
    keywords: ["满足", "愿望成真", "幸福", "丰盛"], keywordsReversed: ["不满足", "物质主义", "失望"],
    meaning: "愿望之牌！你所期盼的即将实现，内心满足，享受这份丰盛。",
    meaningReversed: "即使外在丰盛，内心仍感空虚，检视真正的需求。" },
  { id: 45, name: "Ten of Cups", nameZh: "圣杯十", arcana: "minor", suit: "cups", number: 10, imageEmoji: "🌅",
    keywords: ["完整的爱", "家庭幸福", "圆满", "喜悦"], keywordsReversed: ["家庭失和", "不完美", "理想破灭"],
    meaning: "彩虹下的幸福，爱与喜悦的圆满。珍视你所拥有的一切。",
    meaningReversed: "家庭关系出现裂痕，需要修复和用心经营。" },
  { id: 46, name: "Page of Cups", nameZh: "圣杯侍者", arcana: "minor", suit: "cups", imageEmoji: "🐟",
    keywords: ["创意消息", "直觉", "敏感", "情感探索"], keywordsReversed: ["情绪化", "不成熟", "幻想"],
    meaning: "充满创意和直觉的年轻能量。让自己保持好奇和开放。",
    meaningReversed: "情绪过于敏感或不成熟，需要更多自我认知。" },
  { id: 47, name: "Knight of Cups", nameZh: "圣杯骑士", arcana: "minor", suit: "cups", imageEmoji: "🦢",
    keywords: ["浪漫", "追求", "理想主义", "艺术"], keywordsReversed: ["情绪操控", "不切实际", "逃避"],
    meaning: "浪漫的理想主义者，带着爱意与热情追求美好。",
    meaningReversed: "可能沉溺于幻想，或用情绪来操控他人。" },
  { id: 48, name: "Queen of Cups", nameZh: "圣杯皇后", arcana: "minor", suit: "cups", imageEmoji: "🧜",
    keywords: ["直觉力强", "慈悲", "情感智慧", "疗愈"], keywordsReversed: ["情绪不稳", "依赖", "自我欺骗"],
    meaning: "深邃的情感智慧，充满慈悲和疗愈力。你的直觉从不说谎。",
    meaningReversed: "注意情绪的边界，避免因过于敏感而失去自我。" },
  { id: 49, name: "King of Cups", nameZh: "圣杯国王", arcana: "minor", suit: "cups", imageEmoji: "🌊",
    keywords: ["情感成熟", "智慧", "外交", "平衡"], keywordsReversed: ["情感操控", "压抑情绪", "不稳定"],
    meaning: "在波涛中保持平静，以成熟的情感智慧处理一切人际关系。",
    meaningReversed: "可能在压抑真实感受，或用情绪来控制局面。" },
];

// ── 宝剑（风）14张 ──
const SWORDS: TarotCard[] = [
  { id: 50, name: "Ace of Swords", nameZh: "宝剑王牌", arcana: "minor", suit: "swords", number: 1, imageEmoji: "⚔️",
    keywords: ["清晰", "真相", "突破", "新想法"], keywordsReversed: ["混乱", "谎言", "误解"],
    meaning: "如剑斩乱麻，清晰的真相和洞见带来突破。思维清明，直面现实。",
    meaningReversed: "思维混乱或被谎言蒙蔽，需要更清醒的判断。" },
  { id: 51, name: "Two of Swords", nameZh: "宝剑二", arcana: "minor", suit: "swords", number: 2, imageEmoji: "🙈",
    keywords: ["僵局", "回避", "两难抉择", "内心冲突"], keywordsReversed: ["信息过载", "困惑", "做出选择"],
    meaning: "你正处于两难之中。终究要面对，选择其一。",
    meaningReversed: "信息太多反而更困惑，需要安静下来倾听内心。" },
  { id: 52, name: "Three of Swords", nameZh: "宝剑三", arcana: "minor", suit: "swords", number: 3, imageEmoji: "💔",
    keywords: ["心痛", "悲伤", "分离", "失望"], keywordsReversed: ["疗愈", "原谅", "走出痛苦"],
    meaning: "心痛是真实的，允许自己感受。时间会疗愈，你比想象中更坚强。",
    meaningReversed: "正在走出痛苦，学会原谅和放下，疗愈正在发生。" },
  { id: 53, name: "Four of Swords", nameZh: "宝剑四", arcana: "minor", suit: "swords", number: 4, imageEmoji: "😴",
    keywords: ["休息", "恢复", "冥想", "暂时休战"], keywordsReversed: ["停滞", "精疲力竭", "重新出发"],
    meaning: "你需要休息和恢复。放下战斗，给自己一段安静的空间来充电。",
    meaningReversed: "长期休息变成了停滞，是时候重新出发了。" },
  { id: 54, name: "Five of Swords", nameZh: "宝剑五", arcana: "minor", suit: "swords", number: 5, imageEmoji: "😤",
    keywords: ["冲突", "失败", "自我中心", "代价"], keywordsReversed: ["和解", "和平", "放下争斗"],
    meaning: "即使赢了，代价太大。审视这场争斗是否值得。",
    meaningReversed: "选择和解与和平，放下非赢不可的执念。" },
  { id: 55, name: "Six of Swords", nameZh: "宝剑六", arcana: "minor", suit: "swords", number: 6, imageEmoji: "⛵",
    keywords: ["过渡", "移动", "离开困境", "平静"], keywordsReversed: ["抗拒改变", "留恋过去", "混乱持续"],
    meaning: "离开动荡，驶向平静的水域。你正在走向更好的地方。",
    meaningReversed: "不愿意离开当前困境，转变过程中遭遇阻碍。" },
  { id: 56, name: "Seven of Swords", nameZh: "宝剑七", arcana: "minor", suit: "swords", number: 7, imageEmoji: "🤫",
    keywords: ["策略", "欺骗", "逃避", "单独行动"], keywordsReversed: ["暴露谎言", "良心发现", "坦白"],
    meaning: "需要策略和智慧。但注意：走捷径可能带来长远代价，保持诚信。",
    meaningReversed: "谎言或秘密即将暴露，是时候坦诚面对。" },
  { id: 57, name: "Eight of Swords", nameZh: "宝剑八", arcana: "minor", suit: "swords", number: 8, imageEmoji: "🔒",
    keywords: ["束缚", "受害心态", "限制", "无力感"], keywordsReversed: ["解脱", "重获力量", "打破限制"],
    meaning: "你感到被困，但绑住你的其实是自己的想法。解开束缚从内心开始。",
    meaningReversed: "开始看清束缚的本质，勇敢迈出解脱的第一步。" },
  { id: 58, name: "Nine of Swords", nameZh: "宝剑九", arcana: "minor", suit: "swords", number: 9, imageEmoji: "😰",
    keywords: ["焦虑", "噩梦", "担忧", "内疚"], keywordsReversed: ["走出恐惧", "希望曙光", "面对担忧"],
    meaning: "深夜的焦虑往往被放大。在光天化日下，大多数恐惧都会消散。",
    meaningReversed: "恐惧正在减弱，开始能够理性看待让你担忧的事情。" },
  { id: 59, name: "Ten of Swords", nameZh: "宝剑十", arcana: "minor", suit: "swords", number: 10, imageEmoji: "🌅",
    keywords: ["终结", "失败", "背叛", "黎明前黑暗"], keywordsReversed: ["康复", "重新站起", "拒绝失败"],
    meaning: "这是最黑暗的时刻，但也意味着黎明将至。结局让新的开始成为可能。",
    meaningReversed: "从最低谷重新站起，拒绝被失败击垮，恢复中。" },
  { id: 60, name: "Page of Swords", nameZh: "宝剑侍者", arcana: "minor", suit: "swords", imageEmoji: "🦅",
    keywords: ["好奇心", "消息", "直接", "思维敏锐"], keywordsReversed: ["八卦", "鲁莽", "言辞伤人"],
    meaning: "头脑敏锐，充满求知欲。新消息来临，保持开放和分析能力。",
    meaningReversed: "言辞可能过于犀利，或在传播未经证实的消息。" },
  { id: 61, name: "Knight of Swords", nameZh: "宝剑骑士", arcana: "minor", suit: "swords", imageEmoji: "💨",
    keywords: ["行动迅速", "决断", "雄心", "直接"], keywordsReversed: ["鲁莽冲动", "不计后果", "争强好胜"],
    meaning: "快速果断地行动！目标清晰，斩断一切阻碍，全力冲刺。",
    meaningReversed: "行动过于鲁莽，可能因为缺乏考虑而引发冲突。" },
  { id: 62, name: "Queen of Swords", nameZh: "宝剑皇后", arcana: "minor", suit: "swords", imageEmoji: "🌬️",
    keywords: ["独立", "直接", "清晰判断", "公正"], keywordsReversed: ["冷漠", "刻薄", "偏见"],
    meaning: "用清晰的思维和独立的判断力面对一切。不被情绪左右，公正处事。",
    meaningReversed: "可能因过于冷漠而伤害他人，或判断带有偏见。" },
  { id: 63, name: "King of Swords", nameZh: "宝剑国王", arcana: "minor", suit: "swords", imageEmoji: "⚖️",
    keywords: ["权威", "理性", "真相", "道德判断"], keywordsReversed: ["专制", "操控", "滥用权力"],
    meaning: "以理性和公正治理一切，追求真相与道德。是一位公正的裁断者。",
    meaningReversed: "可能正在滥用权威，或用理性来压制他人的感受。" },
];

// ── 金币（土）14张 ──
const PENTACLES: TarotCard[] = [
  { id: 64, name: "Ace of Pentacles", nameZh: "金币王牌", arcana: "minor", suit: "pentacles", number: 1, imageEmoji: "💰",
    keywords: ["新机遇", "物质繁荣", "实现", "稳固基础"], keywordsReversed: ["错过机遇", "贪婪", "不稳定"],
    meaning: "物质层面的新开始！一个实际的机会或资源正向你伸来，大胆接住。",
    meaningReversed: "机会可能被错过，或对物质的渴望过于强烈。" },
  { id: 65, name: "Two of Pentacles", nameZh: "金币二", arcana: "minor", suit: "pentacles", number: 2, imageEmoji: "🤹",
    keywords: ["平衡", "灵活应变", "多任务", "适应"], keywordsReversed: ["失衡", "过度扩张", "混乱"],
    meaning: "你在同时兼顾多件事，保持灵活，动态平衡是你的超能力。",
    meaningReversed: "同时应付太多，开始失去平衡，需要做出取舍。" },
  { id: 66, name: "Three of Pentacles", nameZh: "金币三", arcana: "minor", suit: "pentacles", number: 3, imageEmoji: "🏗️",
    keywords: ["合作", "技艺", "学习", "团队"], keywordsReversed: ["缺乏合作", "平庸", "漠视反馈"],
    meaning: "精湛的技艺与团队合作带来成就。谦虚学习，与他人协力。",
    meaningReversed: "团队合作不顺，或不愿意接受批评和建议。" },
  { id: 67, name: "Four of Pentacles", nameZh: "金币四", arcana: "minor", suit: "pentacles", number: 4, imageEmoji: "🤑",
    keywords: ["保守", "控制", "安全感", "守财"], keywordsReversed: ["放开", "慷慨", "失去控制"],
    meaning: "守护资源是明智的，但过度紧握可能阻碍成长。学会适度放手。",
    meaningReversed: "开始学会慷慨和分享，释放执着。" },
  { id: 68, name: "Five of Pentacles", nameZh: "金币五", arcana: "minor", suit: "pentacles", number: 5, imageEmoji: "🥶",
    keywords: ["物质困难", "贫乏感", "孤立", "失去"], keywordsReversed: ["康复", "接受帮助", "度过难关"],
    meaning: "困难时期，但帮助就在附近。放下骄傲，接受支持，你不是一个人。",
    meaningReversed: "最艰难的时期正在过去，接受帮助让你渡过难关。" },
  { id: 69, name: "Six of Pentacles", nameZh: "金币六", arcana: "minor", suit: "pentacles", number: 6, imageEmoji: "🤲",
    keywords: ["慷慨", "给予", "接受", "平衡互惠"], keywordsReversed: ["吝啬", "不平等", "有条件的给予"],
    meaning: "慷慨的给予与接受形成美好的循环。无论施予或接受，都值得尊重。",
    meaningReversed: "给予或接受中存在不平等，检视关系中的权力动态。" },
  { id: 70, name: "Seven of Pentacles", nameZh: "金币七", arcana: "minor", suit: "pentacles", number: 7, imageEmoji: "🌱",
    keywords: ["评估", "耐心", "长期投资", "审视"], keywordsReversed: ["缺乏远见", "急于求成", "放弃"],
    meaning: "你已辛勤耕耘，现在是评估成果的时候。耐心是美德，种下的将会收获。",
    meaningReversed: "急于看到结果而失去耐心，或在该坚持时选择放弃。" },
  { id: 71, name: "Eight of Pentacles", nameZh: "金币八", arcana: "minor", suit: "pentacles", number: 8, imageEmoji: "🔨",
    keywords: ["勤奋", "技艺精进", "专注", "工匠精神"], keywordsReversed: ["完美主义", "缺乏专注", "偷工减料"],
    meaning: "专注于技艺的精进，每一个细节都用心对待。工匠精神带来卓越。",
    meaningReversed: "可能陷入完美主义，或做事不够专注投入。" },
  { id: 72, name: "Nine of Pentacles", nameZh: "金币九", arcana: "minor", suit: "pentacles", number: 9, imageEmoji: "🌿",
    keywords: ["富足", "独立", "自给自足", "享受"], keywordsReversed: ["过度工作", "物质依赖", "缺乏自给"],
    meaning: "通过努力获得了独立和富足，尽情享受这份美好。你值得拥有。",
    meaningReversed: "可能工作过度而忽略享受，或在物质上过度依赖他人。" },
  { id: 73, name: "Ten of Pentacles", nameZh: "金币十", arcana: "minor", suit: "pentacles", number: 10, imageEmoji: "🏡",
    keywords: ["传承", "家族繁荣", "稳定", "长久成就"], keywordsReversed: ["家族冲突", "失去遗产", "不稳定"],
    meaning: "世代积累的繁荣与稳定。家族的幸福、物质的丰盛是长期努力的果实。",
    meaningReversed: "家族关系中存在紧张，或长期建立的稳定出现动摇。" },
  { id: 74, name: "Page of Pentacles", nameZh: "金币侍者", arcana: "minor", suit: "pentacles", imageEmoji: "📚",
    keywords: ["学习", "实践", "新机会", "专注"], keywordsReversed: ["缺乏专注", "不切实际", "拖延"],
    meaning: "认真学习，脚踏实地。新的实际机会正在等你，保持专注和勤奋。",
    meaningReversed: "可能缺乏专注力，或过于理想化而忽略实际行动。" },
  { id: 75, name: "Knight of Pentacles", nameZh: "金币骑士", arcana: "minor", suit: "pentacles", imageEmoji: "🐂",
    keywords: ["踏实", "可靠", "勤奋", "耐心"], keywordsReversed: ["固执", "停滞", "无聊"],
    meaning: "稳扎稳打的可靠力量。慢而稳定地前行，你的坚持终将得到回报。",
    meaningReversed: "过于固执保守，导致停滞不前，需要适当调整节奏。" },
  { id: 76, name: "Queen of Pentacles", nameZh: "金币皇后", arcana: "minor", suit: "pentacles", imageEmoji: "🌻",
    keywords: ["务实", "养育", "丰盛", "接地气"], keywordsReversed: ["物质主义", "自私", "工作生活失衡"],
    meaning: "充满温暖和实际智慧，用爱和务实照顾好家园与事业。",
    meaningReversed: "可能过于看重物质，或在照顾他人时忽略了自己。" },
  { id: 77, name: "King of Pentacles", nameZh: "金币国王", arcana: "minor", suit: "pentacles", imageEmoji: "🏦",
    keywords: ["财富", "商业智慧", "稳定", "成就"], keywordsReversed: ["固执保守", "物质至上", "吝啬"],
    meaning: "通过勤奋和智慧积累了丰厚的物质成就。慷慨分享你的富足。",
    meaningReversed: "可能因过于看重物质而变得固执或吝啬。" },
];

export const ALL_CARDS: TarotCard[] = [...MAJOR_ARCANA, ...WANDS, ...CUPS, ...SWORDS, ...PENTACLES];

export function drawCards(count: number): TarotCard[] {
  return [...ALL_CARDS].sort(() => Math.random() - 0.5).slice(0, count);
}

export const SPREADS = [
  { id: "single", name: "单牌占卜", description: "快速洞察当下能量", count: 1, emoji: "🃏", positions: ["当下能量"] },
  { id: "three", name: "三牌展开", description: "过去・现在・未来", count: 3, emoji: "🌙", positions: ["过去", "现在", "未来"] },
  { id: "celtic", name: "凯尔特十字", description: "深度全面解读", count: 5, emoji: "✨", positions: ["核心", "挑战", "过去", "未来", "结果"] },
];
